### ISSUE TITLE
"Deploy Theme" action only works with a branch named 'main'.

### ISSUE THREAD

**Issue by mkromann** [wesselvanree/shopify-theme-tailwind#8]
I noticed that the 'dist' branch wasn't created automatically when I made my first commit. My HEAD branch was named 'master' but I changed it to 'main', and it worked flawlessly.

I guess it could be useful to note that in the documentation. Or add the most used head branch names to the action (I don't know Github Actions, so not sure what's possible). 

Anyhow, thank you :)

**Comment by wesselvanree** [comment]
Hi, thank you for mentioning this problem.

If you want to use the `master` as your default branch, the only thing you have to do is change `main` to `master` in `.github/workflows/deploy.yml`. This results in the following `deploy.yml` file:

```yml
name: Deploy Theme

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
          rm .gitignore
          mv .gitignore.build .gitignore

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: dist # The branch the action should deploy to.
          folder: shopify # The folder the action should deploy.

```

I will add this to the installation part of the docs.
